---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: demo service
  annotations:
    github.com/project-slug: rockesh7/backstage-demo
spec:
  type: service
  owner: team-a
  lifecycle: experimental
  dependsOn:
    - component:example-website
